.objs/execution/executing_node.o: srcs/execution/executing_node.c \
  incs/sh.h libs/libft/incs/libft.h libs/libft/incs/get_next_line.h \
  libs/printf/incs/ft_printf.h incs/define.h incs/struct.h \
  libs/logger/incs/logger.h libs/logger/incs/logger_utils.h incs/enum.h

incs/sh.h:

libs/libft/incs/libft.h:

libs/libft/incs/get_next_line.h:

libs/printf/incs/ft_printf.h:

incs/define.h:

incs/struct.h:

libs/logger/incs/logger.h:

libs/logger/incs/logger_utils.h:

incs/enum.h:
